name:                notes
version:             0.1.0.0
github:              "lsund/notes"
license:             BSD3
author:              "Ludvig Sundström"
maintainer:          "lud.sund@gmail.com"
copyright:           "2020 Ludvig Sundström"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/lsund/notes>

dependencies:
- base >= 4.7 && < 5
- brick
- text
- vty
- microlens
- microlens-th
- split
- directory
- aeson
- bytestring
- pretty-simple
- transformers
- time
- text-zipper
- safe
- utility-ht

library:
  source-dirs: src

executables:
  notes:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notes

tests:
  notes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notes
